env:
  es2021: true
  node: true
extends: [standard-with-typescript, plugin:prettier/recommended, plugin:react/recommended, plugin:react-hooks/recommended, plugin:react/jsx-runtime]
overrides: []
parserOptions:
  ecmaVersion: 2022
  sourceType: module
  project: ["tsconfig.json"]
rules: {
  '@typescript-eslint/strict-boolean-expressions': 0
}
ignorePatterns: [node_modules/**, dist/**]
