env:
  es2021: true
  node: true
extends: [standard-with-typescript, plugin:prettier/recommended]
overrides: []
parserOptions:
  ecmaVersion: 2022
  sourceType: module
  project: ["tsconfig.json"]
rules: {}
ignorePatterns: [node_modules/**, dist/**]
